### ISSUE TITLE
Site not fitting screen

### ISSUE THREAD

**Issue by manahan-joseph** [leviv/Mikes-Got-Style#2]
When I go to the 314 site, several of the links are not centered and slide off the edge of the screen. My resolution is 2560 x 1440 if that matters.

![mgs](https://user-images.githubusercontent.com/828565/34965284-8b4e8c70-fa18-11e7-8d4f-c2c9428a125e.PNG)

**Comment by leviv** [comment]
Does the link http://www.cs.utexas.edu/~scottm/cs314/ work as expected?

**Comment by manahan-joseph** [comment]
Yes.

**Comment by leviv** [comment]
Ok, then I see what the problem is. I'll update the extension right now so that site address should work in a few minutes
